### ISSUE TITLE
Deploy (and Rendering?) of PDF Broken?

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3book#383] opened 2022-06-29 09:23 UTC
The README-link to the PDF as rendered by the CI points to https://mlr3book.mlr-org.com/mlr3book.pdf, but it is dead, where does the PDF get deployed to?

When I render it locally, some of the unicode chars don't get rendered correctly, but I don't know if this is a problem with my setup. E.g. beginning of chatper 3.1 Task Types:
![image](https://user-images.githubusercontent.com/15801081/176401606-01e5f281-0806-4127-8dd1-74accc4bf525.png)

**Comment by mllg** [comment] 2022-06-29 21:34
The PDF does not seem to get rendered currently by the CI. We should maybe just remove the link from the website?

I cannot reproduce the encoding problem locally.

**Comment by pat-s** [comment] 2022-07-08 06:50
PDF building and deployment works since the start, it's only a naming issue. The output was named `mlr3-book.pdf` (wrong) and hence the link was not working.
Thanks for mentioning.

I don't see the encoding issue mentioned in the PDF output. 

Fixed in https://github.com/mlr-org/mlr3book/commit/688643eeed8048a264d0192a2b128cf236de168c.

**Closed by pat-s** 2022-07-08 06:50 UTC
