### ISSUE TITLE
impossible to copy code when pages are open to full width of the page

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#133] opened 2020-02-04 12:49 UTC
This might be an issue with bookdown, but when my browser is at full screen width and I bring my cursor over to the edge of the screen, the entire right and left margins of the main text screen are clickable to move one section before/after the current one. However, this prevents me from copying the code by clicking on the "copy code" icon in the top right corner of the code snippets:
![image](https://user-images.githubusercontent.com/1280767/73746224-02069700-4755-11ea-804a-df8060ebd1a3.png)

I worked around this by making my screen narrower, and then the margin navigation arrows disappear and I am able to use the copy code button

**Comment by pat-s** [comment] 2020-02-04 13:49
For me (macOS, Firefox) everything works as expected on full browser width.

Not sure if we can/should change something like that. 
If there is really a glitch it might relate to bookdown.

If the issue is still bugging you, a GIF might help to showcase the problem better.

**Comment by nickreich** [comment] 2020-02-04 16:18
I'm using macOS, Chrome, on a 13" laptop screen. 
This is the last post I'll make about this, only because I'm a stickler for these kinds of details. The default way the mlr3 book loads just looks more clumsy and cluttered than other bookdown docs load for me on the same browser. 
FWIW, I have this issue with mlr3 but not with other bookdown-like docs, like the Stan manual. This is a screenshot of the Stan manual
![image](https://user-images.githubusercontent.com/1280767/73763625-f9708980-4771-11ea-9c82-d9f037ed5fc0.png)
Note how the Table of Contents column is narrow and the arrows for navigation are completely out of the way of the content of the book.

This is the mlr3 book:
![image](https://user-images.githubusercontent.com/1280767/73763697-1311d100-4772-11ea-8e7f-77bcfc98a3fa.png)
The scalings are different (the table of contents column is wider, the main content space is narrower) and the navigation arrows overlap the text. If there were more space for the side arrows, then they wouldn't overlap the code copy button.

**Comment by mllg** [comment] 2020-02-04 16:42
I can reproduce by increasing font size / zoom on firefox.

**Comment by mllg** [comment] 2020-02-04 16:48
https://github.com/mlr-org/mlr3book/blob/ba2868d66e46cd1e051999af899b8e958a92b337/bookdown/style.css#L7

Some custom CSS to make the book more appealing I guess?

**Comment by pat-s** [comment] 2020-02-04 16:50
Thanks Nick, now I understand.

Yes, I'll fix it.

**Comment by mllg** [comment] 2020-02-12 19:56
Fixed now.

**Closed by mllg** 2020-02-12 19:56 UTC
Labels: book-design/visual
