### ISSUE TITLE
Explain use of the .() function in performance rank calculation

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#134] opened 2020-02-04 12:58 UTC
I'm not familiar with this use of the `.(...)` function that is used in section 2.6.2. Perhaps others might be similarly confused? Consider adding a code comment or brief textual explanation of what the second line of this code does? 
```
tab = bmr$aggregate(measures)
ranks = tab[, .(learner_id, rank_train = rank(-auc_train), rank_test = rank(-auc_test)), by = task_id]
```
I can obviously see from the results what the output is, but explanation would be helpful.

**Comment by pat-s** [comment] 2020-02-04 13:46
I see the point but I don't think we should start explaining syntax from certain packages (here {data.table}).

**Comment by nickreich** [comment] 2020-02-04 14:00
I still can't figure out how to even determine what function this is using or how to look for help on it. E.g., `?.` gave me nothing. And I think you want the documentation to be self-explanatory. But I agree that you may not want to be in the business of explaining other people's packages.

So maybe just providing a pointer to the relevant `data.table` help file with something like "(To learn more about the `.(...)` syntax used here, please visit the [data.table](add link here) documentation site."

**Comment by pat-s** [comment] 2020-02-04 14:09
I fully see your point here. The problem is that if we do this once we would need to add this piece of information for every instance we use this notation.

Theoretically spoken this would then also apply to all other custom syntax of packages, e.g. the pipe `%>%`.
(Of course I know that there are differences because the latter is more popular; I just don't know atm how such a problems are addressed in the best way.)

But yeah, maybe a one sentence explanation what this line is about **in general** might be helpful. But this is different to explaining the data.table syntax in detail.

Let's see what others think.

**Comment by mllg** [comment] 2020-02-04 15:08
1. I agree that we should at least link to some helpful documentation on data.table.
2. It would be better to write the aggregation down without data.table, e.g. with the `aggregate()` function from `stats`. Maybe not instead of the data.table syntax, but additionally as an alternative.

**Closed** 2020-02-12 09:04 UTC
Labels: feedback
