### ISSUE TITLE
two mistakes in mlr3 book

### ISSUE THREAD

**Issue by ayue2019** [mlr-org/mlr3book#287] opened 2022-02-15 14:40 UTC
1. In section 3 performance evaluation and comparision.
......
We can also plot the predictions of individual models:

```
# learner predictions for the first fold
rr$filter(1)
autoplot(rr, type = "prediction")
```
that's not the first fold but all folds, it should be 
```
autoplot(rr$filter(1), type = "prediction")
```

2. Also in section 3 performance evaluation and comparision.

......
We can also plot ROC curves. We filter the BenchmarkResult to only contain a single Task, then we simply plot the result:
```
bmr_small = bmr$clone()$filter(task_id = "german_credit")
autoplot(bmr_small, type = "roc")
```
but i got an error:
```
Error: Unable to convert benchmark results with multiple resamplings.
```

**Comment by larskotthoff** [comment] 2022-02-15 21:14
Thanks for your report. In the first example, `$filter()` modifies the `rr` object, so it's not necessary to filter again. The second example works fine in the book (all the code is executed when the book is rendered), so the problem is almost certainly something in your environment (maybe you ran some other code before then that overwrote some of the variables?).

I'm closing this, but feel free to reopen if I missed something.

**Closed by larskotthoff** 2022-02-15 21:14 UTC
